[versions]
java = "21"
kotlin = "2.2.20"
spotless = "6.25.0"
detekt = "1.23.8"
junit = "5.13.4"
kotlinx-serialization = "1.9.0"
dokka = "2.2.0"
spring-boot-version = "4.1.1"
mongodb-driver = "5.11.1"
logback = "1.6.5"
jackson = "3.1.7"
tomcat = "11.0.26"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot-version" }
spring-boot-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
mongodb-driver-bom = { module = "org.mongodb:mongodb-driver-bom", version.ref = "mongodb-driver" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
jackson-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson" }
tomcat-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
tomcat-el = { module = "org.apache.tomcat.embed:tomcat-embed-el", version.ref = "tomcat" }
tomcat-websocket = { module = "org.apache.tomcat.embed:tomcat-embed-websocket", version.ref = "tomcat" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot-version" }
